"""Second migration

Revision ID: 97657d1fa6b9
Revises: f9eb5e0b78e5
Create Date: 2025-03-03 19:39:16.525167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97657d1fa6b9'
down_revision = 'f9eb5e0b78e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('edited_timestamp', sa.DateTime(), nullable=True))
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('edited_timestamp')
        batch_op.drop_column('edited')

    # ### end Alembic commands ###
